<a href="https://colab.research.google.com/github/christophermalone/DSCI325/blob/main/Module2_Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 2 | Part 2: Pre-processing of Data Files - Part II

The notebook will cover additional tasks regarding the pre-processing of a data file.  The command line stream editor SED will be used in this notebook.  SED was introduced in Module 2 | Part 1.

<table width='100%' ><tr><td bgcolor='green'></td></tr></table>

### Example 2.2.1

This example uses data regarding the location and contact information for most Ski Areas/Resorts in North America. The data file was obtained from the Point-of-Interest website. 

<i>Data Source</i>: http://www.poi-factory.com/

<table width='100%' ><tr><td bgcolor='green'></td></tr></table>

These two data files have been saved into the following folder in Colab.

<p align='center'><img src="https://drive.google.com/uc?export=view&id=1w5maZ6u0yuR6ZIfVw40JUlziNzBFx0wi"></p>

In [1]:
#Taking a look at first few lines of data file
!head /content/sample_data/Ski_Areas_NorthAmerica.csv

-114.215597,51.08296,"Canada Olympic Park-Calgary,AB - Snow Conditions: Call  (403) 247-5452","88 Canada Olympic Road SW, Calgary,AB"
-113.682207,52.304426,"Canyon Ski Area-Red Deer,AB - Snow Conditions: Call  (403) 346-7003","Site 8 Box 26 RR 2 Lcd 1, Red Deer,AB"
-114.413802,49.31866,"Castle Mountain-Pincher Creek,AB - Snow Conditions: Call  (403) 543-4500","Box 610 Pincher Creek,  Banff National Park,AB"
-113.475781,53.53452,"Drumheller Valley Ski Club-Drumheller,AB - Snow Conditions: Call  (403) 823-2277","1695 6th Ave SW, Drumheller,AB"
-113.479045,53.53365,"Edmonton Ski Club-Edmonton,AB - Snow Conditions: Call  (780) 465-0852","9613 96 Ave NW, Edmonton,AB"
-118.604365,55.994589,"Fairview Ski Hill-Fairview,AB - Snow Conditions: Call  (780) 835-4725","PO Box 618, Fairview,AB"
-115.194227,50.818108,"Fortress Mountain-Fortress Mountain,AB - Snow Conditions: Call  (403) 591-7108","1 Fortress Mountain Rd, Kananaskis,AB"
-110.26036,49.656765,"Hidden Valley-Cypress Hills Provincial Park,

The following are relevent regarding the task of reading in this data.


1.   This is a comma separated values file, i.e. four fields are seperated by commas
2.   Some fields contain commas; which are not to be confused by commas that are used to seperate the fields
3.   Quotes are used to assist with the specification of a field in this situation -- this is somewhat common



Let us consider Line #1.  The commas highligted here deliniate the four fields.

<p align='center'><img src="https://drive.google.com/uc?export=view&id=18iLlYT6M-aN10dvZ2LCBkiDzbp3CQun_"></p>


Commas within a field are ignored because the quotes are being used to assist in the specification of the field.
<p align='center'><img src="https://drive.google.com/uc?export=view&id=1P2vL-OWNxKEj8Ls1mwkeZjuJmgKfnaJx"></p>


##  Reading the inital data file into R

To begin, let us read this data file into R.  Once again, this is an iPython Notebook, so R Magic will be used in each code block to run the R commands.

In [2]:
%load_ext rpy2.ipython

In [3]:
#Read the *.csv file into R; provide names for each field as well
%%R

SkiAreas <- read.csv('/content/sample_data/Ski_Areas_NorthAmerica.csv',header=FALSE)
names(SkiAreas) <- c("Longitude", "Latitude", "SkiResort", "PostalAddress")

#View the data.frame
head(SkiAreas)

  Longitude Latitude
1 -114.2156 51.08296
2 -113.6822 52.30443
3 -114.4138 49.31866
4 -113.4758 53.53452
5 -113.4790 53.53365
6 -118.6044 55.99459
                                                                         SkiResort
1           Canada Olympic Park-Calgary,AB - Snow Conditions: Call  (403) 247-5452
2              Canyon Ski Area-Red Deer,AB - Snow Conditions: Call  (403) 346-7003
3         Castle Mountain-Pincher Creek,AB - Snow Conditions: Call  (403) 543-4500
4 Drumheller Valley Ski Club-Drumheller,AB - Snow Conditions: Call  (403) 823-2277
5            Edmonton Ski Club-Edmonton,AB - Snow Conditions: Call  (780) 465-0852
6            Fairview Ski Hill-Fairview,AB - Snow Conditions: Call  (780) 835-4725
                                   PostalAddress
1          88 Canada Olympic Road SW, Calgary,AB
2          Site 8 Box 26 RR 2 Lcd 1, Red Deer,AB
3 Box 610 Pincher Creek,  Banff National Park,AB
4                 1695 6th Ave SW, Drumheller,AB
5                    9613 9

Review the contents of the data.frame printed above. Notice that the commas within the quoted string are retained when this *.csv file is read into R; however, the commas between the fields are used to deliniate the four fields in this data file.

## Pre-Processing of the Data File

<strong>Goal:</strong> Suppose the goal is to read-in **only** the following information from the existing data file.

1.   Longitude
2.   Latitude
3.   Phone Number



Consider once again the structure of each line in this text file.

In [4]:
!head /content/sample_data/Ski_Areas_NorthAmerica.csv

-114.215597,51.08296,"Canada Olympic Park-Calgary,AB - Snow Conditions: Call  (403) 247-5452","88 Canada Olympic Road SW, Calgary,AB"
-113.682207,52.304426,"Canyon Ski Area-Red Deer,AB - Snow Conditions: Call  (403) 346-7003","Site 8 Box 26 RR 2 Lcd 1, Red Deer,AB"
-114.413802,49.31866,"Castle Mountain-Pincher Creek,AB - Snow Conditions: Call  (403) 543-4500","Box 610 Pincher Creek,  Banff National Park,AB"
-113.475781,53.53452,"Drumheller Valley Ski Club-Drumheller,AB - Snow Conditions: Call  (403) 823-2277","1695 6th Ave SW, Drumheller,AB"
-113.479045,53.53365,"Edmonton Ski Club-Edmonton,AB - Snow Conditions: Call  (780) 465-0852","9613 96 Ave NW, Edmonton,AB"
-118.604365,55.994589,"Fairview Ski Hill-Fairview,AB - Snow Conditions: Call  (780) 835-4725","PO Box 618, Fairview,AB"
-115.194227,50.818108,"Fortress Mountain-Fortress Mountain,AB - Snow Conditions: Call  (403) 591-7108","1 Fortress Mountain Rd, Kananaskis,AB"
-110.26036,49.656765,"Hidden Valley-Cypress Hills Provincial Park,

The <strong>!cat</strong> command can be used to make a copy of the orginial text file.

In [5]:
!cat /content/sample_data/Ski_Areas_NorthAmerica.csv > /content/sample_data/Ski_Areas_NorthAmerica_v2.csv

Verify that a copy was created and put into the same directory.

In [8]:
!ls /content/sample_data/

Ski_Areas_NorthAmerica.csv  Ski_Areas_NorthAmerica_v2.csv


The following sed command will accomplish the following:


1.   Conduct a search
2.   Find the first double quote, i.e. "
3.   Continue the search until you find Call__ , i.e. Call followed by two spaces
4.   Replace string found with nothing



<p align='center'><img src="https://drive.google.com/uc?export=view&id=1BZ1FCe3NAwYtVwQtIASuse8m_GUpuWNo"></p>




In [9]:
#The following sed command will reduce the contents of the third field
!sed 's/".*Call  //' /content/sample_data/Ski_Areas_NorthAmerica_v2.csv > /content/sample_data/Ski_Areas_NorthAmerica_v3.csv

In [10]:
#Looking at the resulting output from this sed search and replace
!head /content/sample_data/Ski_Areas_NorthAmerica_v3.csv

-114.215597,51.08296,(403) 247-5452","88 Canada Olympic Road SW, Calgary,AB"
-113.682207,52.304426,(403) 346-7003","Site 8 Box 26 RR 2 Lcd 1, Red Deer,AB"
-114.413802,49.31866,(403) 543-4500","Box 610 Pincher Creek,  Banff National Park,AB"
-113.475781,53.53452,(403) 823-2277","1695 6th Ave SW, Drumheller,AB"
-113.479045,53.53365,(780) 465-0852","9613 96 Ave NW, Edmonton,AB"
-118.604365,55.994589,(780) 835-4725","PO Box 618, Fairview,AB"
-115.194227,50.818108,(403) 591-7108","1 Fortress Mountain Rd, Kananaskis,AB"
-110.26036,49.656765,(403) 893-3961","3314 17 Ave SW, Medicine Hat,AB"
-110.019178,54.440092,(780) 594-5564","PO Box 390 Stn Main, Cold Lake, AB"
-118.082383,52.800994,(780) 852-3816","1 Marmot Basin Road, Jasper,AB"


Next, the following sed command will accomplish the following:


1.   Conduct a search
2.   Find the first double quote, i.e. "
3.   Continue the search until the end-of-line
4.   Replace string found with nothing



<p align='center'><img src="https://drive.google.com/uc?export=view&id=1gu6bw2Xd-Ia-09JROnEHBHR_csYJYDHq"></p>


<strong>Comment:</strong>  A $ is used to identify the end of a line in sed  and a ^ is used to identify the beginning of a line in sed.

In [11]:
#The following sed command will find-and-replace the end of each line
!sed 's/".*$//' /content/sample_data/Ski_Areas_NorthAmerica_v3.csv > /content/sample_data/Ski_Areas_NorthAmerica_v4.csv

In [12]:
#Looking at the resulting output from this sed search and replace
!head /content/sample_data/Ski_Areas_NorthAmerica_v4.csv

-114.215597,51.08296,(403) 247-5452
-113.682207,52.304426,(403) 346-7003
-114.413802,49.31866,(403) 543-4500
-113.475781,53.53452,(403) 823-2277
-113.479045,53.53365,(780) 465-0852
-118.604365,55.994589,(780) 835-4725
-115.194227,50.818108,(403) 591-7108
-110.26036,49.656765,(403) 893-3961
-110.019178,54.440092,(780) 594-5564
-118.082383,52.800994,(780) 852-3816


<table width='100%' ><tr><td bgcolor='orange'></td></tr></table>

## Aside -- Getting the State/Providence from each line



In [13]:
#Contents of original data file
!head /content/sample_data/Ski_Areas_NorthAmerica.csv

-114.215597,51.08296,"Canada Olympic Park-Calgary,AB - Snow Conditions: Call  (403) 247-5452","88 Canada Olympic Road SW, Calgary,AB"
-113.682207,52.304426,"Canyon Ski Area-Red Deer,AB - Snow Conditions: Call  (403) 346-7003","Site 8 Box 26 RR 2 Lcd 1, Red Deer,AB"
-114.413802,49.31866,"Castle Mountain-Pincher Creek,AB - Snow Conditions: Call  (403) 543-4500","Box 610 Pincher Creek,  Banff National Park,AB"
-113.475781,53.53452,"Drumheller Valley Ski Club-Drumheller,AB - Snow Conditions: Call  (403) 823-2277","1695 6th Ave SW, Drumheller,AB"
-113.479045,53.53365,"Edmonton Ski Club-Edmonton,AB - Snow Conditions: Call  (780) 465-0852","9613 96 Ave NW, Edmonton,AB"
-118.604365,55.994589,"Fairview Ski Hill-Fairview,AB - Snow Conditions: Call  (780) 835-4725","PO Box 618, Fairview,AB"
-115.194227,50.818108,"Fortress Mountain-Fortress Mountain,AB - Snow Conditions: Call  (403) 591-7108","1 Fortress Mountain Rd, Kananaskis,AB"
-110.26036,49.656765,"Hidden Valley-Cypress Hills Provincial Park,

The State/Providence appears to be last two characters on each line (when the quote is ignored).  The more powerful AWK command line stream editor will be used to pull off the State/Providence abbreviations from each line.  


1.   {print ...} print the contents
2.   $0 specifies each line
3.   substr(*line*, *starting position*, *number of characters*)
4.   \> push contents being printed into a text file



In [14]:
#Pull off the State/Providence abbreviation from each line; 
!awk '{print substr($0,length($0)-3,2)}' /content/sample_data/Ski_Areas_NorthAmerica.csv > /content/sample_data/SkiAreas_NorthAmerica_States.csv

In [15]:
#Review of top/bottom few lines
!head /content/sample_data/SkiAreas_NorthAmerica_States.csv

!tail /content/sample_data/SkiAreas_NorthAmerica_States.csv

AB
AB
AB
AB
AB
AB
AB
AB
AB
AB
WI
WY
WY
WY
WY
WY
WY
WY
WY
WY


<table width='100%' ><tr><td bgcolor='orange'></td></tr></table>



## Reading the Pre-Processed Data File into R

The following snip-if of R code will readin the pre-processed data file.  The file is lacking field names; therefore these have been added to this data.frame.

In [16]:
#Read the *.csv file into R; provide names for each field as well
%%R

SkiAreas <- read.csv('/content/sample_data/Ski_Areas_NorthAmerica_v4.csv',header=FALSE)
names(SkiAreas) <- c("Longitude", "Latitude", "Phone")

#View the structure and head of the data.frame
str(SkiAreas)
 cat('\n')
 cat('The contents of the SkiArea data.frame:')
 cat('\n\n')
head(SkiAreas)

'data.frame':	580 obs. of  3 variables:
 $ Longitude: num  -114 -114 -114 -113 -113 ...
 $ Latitude : num  51.1 52.3 49.3 53.5 53.5 ...
 $ Phone    : chr  "(403) 247-5452" "(403) 346-7003" "(403) 543-4500" "(403) 823-2277" ...

The contents of the SkiArea data.frame:

  Longitude Latitude          Phone
1 -114.2156 51.08296 (403) 247-5452
2 -113.6822 52.30443 (403) 346-7003
3 -114.4138 49.31866 (403) 543-4500
4 -113.4758 53.53452 (403) 823-2277
5 -113.4790 53.53365 (780) 465-0852
6 -118.6044 55.99459 (780) 835-4725


### Simple String Manipulation using Base R

There are commands to manipulate strings in Base R.  For example, strsplit() function can be used to split a string.  The split= parameter specifies the character for which the split will be done upon.

Notice that the structure of the output returned by strsplit() function is three-dimensional table which is atypical in practice.

In [ ]:
%%R

strsplit(SkiAreas$Phone,split='[(]')[1:3]

[[1]]
[1] ""              "403) 247-5452"

[[2]]
[1] ""              "403) 346-7003"

[[3]]
[1] ""              "403) 543-4500"



The structure of the output returned from the strsplit() function in Base R is not optimal.

<p align='center'><img src="https://drive.google.com/uc?export=view&id=1-epyvMbfUNyZ1NG-GxM4G0ZGBr_MRt-k"></p>

The unlist() function in R can be used to collapse a higher dimensional table into a vector in R; however, there will need to be additional manipulation of this vector in order to retain only the area code from each ski resort.

In [ ]:
%%R

unlist(strsplit(SkiAreas$Phone,split='[(]'))[1:6]

[1] ""              "403) 247-5452" ""              "403) 346-7003"
[5] ""              "403) 543-4500"


### Simple String Manipulation using TidyVerse

The string manipulation functions in the tidyverse package are more robust than the functions in base R.

In [ ]:
#Load the tidyverse package in R
%%R

library(tidyverse)

The seperate() function in tidyverse will be used for the task of separating out the area code.  

1.   data= | data.frame to work with
2.   col= | which column in data.frame do you want to separate
3.   into= | name the new columns
4.   sep=[...] | identify what character(s) will be used to separate the desired column



In [22]:
%%R

head(separate(data=SkiAreas, col=Phone, into=c("Col1", "Col2", "Col3"), sep="[()]"))

  Longitude Latitude Col1 Col2      Col3
1 -114.2156 51.08296       403  247-5452
2 -113.6822 52.30443       403  346-7003
3 -114.4138 49.31866       403  543-4500
4 -113.4758 53.53452       403  823-2277
5 -113.4790 53.53365       780  465-0852
6 -118.6044 55.99459       780  835-4725


The following is more common dplyr processing of this command.


1.   Identify data.frame
2.   %>% is aking to > and pushes the output along head in the chain/pipe
3.   Output at end of chain is being put into a new data.frame named SkiAreas_withAreaCode



In [23]:
%%R

(SkiAreas 
      %>% separate(col=Phone, into=c(NA, "AreaCode", NA), sep = "[()]") 
) -> SkiAreas_withAreaCode

str(SkiAreas_withAreaCode)
cat('\n')
head(SkiAreas_withAreaCode)

'data.frame':	580 obs. of  3 variables:
 $ Longitude: num  -114 -114 -114 -113 -113 ...
 $ Latitude : num  51.1 52.3 49.3 53.5 53.5 ...
 $ AreaCode : chr  "403" "403" "403" "403" ...

  Longitude Latitude AreaCode
1 -114.2156 51.08296      403
2 -113.6822 52.30443      403
3 -114.4138 49.31866      403
4 -113.4758 53.53452      403
5 -113.4790 53.53365      780
6 -118.6044 55.99459      780


The following lines of code accomplish the following:

1.   group_by initates a grouping variable so that counts will be done by AreaCode
2.   summarize() function computes a count/tally for each AreaCode
3.   arrange() sort the list in descending order
4.   head() returns the top 6 in the list



In [24]:
%%R

(SkiAreas_withAreaCode 
  %>% group_by(AreaCode)
  %>% summarise(Count = n())
  %>% arrange(desc(Count))
  %>% head()
)

# A tibble: 6 × 2
  AreaCode Count
  <chr>    <int>
1 800         52
2 603         20
3 970         20
4 207         18
5 802         18
6 406         17


Consider the following changes to the chain of dplyr commands
1.   Only the top 10 area codes used
2.   Specify a link for each area code

In [25]:
%%R

(SkiAreas_withAreaCode 
  %>% group_by(AreaCode)
  %>% summarise(Count = n())
  %>% arrange(desc(Count))
  %>% head(10)
  %>% mutate(Link=paste("https://en.wikipedia.org/wiki/Area_code_",AreaCode,sep=''))
)

# A tibble: 10 × 3
   AreaCode Count Link                                       
   <chr>    <int> <chr>                                      
 1 800         52 https://en.wikipedia.org/wiki/Area_code_800
 2 603         20 https://en.wikipedia.org/wiki/Area_code_603
 3 970         20 https://en.wikipedia.org/wiki/Area_code_970
 4 207         18 https://en.wikipedia.org/wiki/Area_code_207
 5 802         18 https://en.wikipedia.org/wiki/Area_code_802
 6 406         17 https://en.wikipedia.org/wiki/Area_code_406
 7 888         17 https://en.wikipedia.org/wiki/Area_code_888
 8 530         14 https://en.wikipedia.org/wiki/Area_code_530
 9 877         14 https://en.wikipedia.org/wiki/Area_code_877
10 208         13 https://en.wikipedia.org/wiki/Area_code_208


Finally, use the ifelse() function to ignore the AreaCode=800 when constructing hyperlinks.


In [26]:
%%R

(SkiAreas_withAreaCode 
  %>% group_by(AreaCode)
  %>% summarise(Count = n())
  %>% arrange(desc(Count))
  %>% head(10)
  %>% mutate(Link=ifelse(AreaCode=='800',"NA",paste("https://en.wikipedia.org/wiki/Area_code_",AreaCode, sep='')))
) 

# A tibble: 10 × 3
   AreaCode Count Link                                       
   <chr>    <int> <chr>                                      
 1 800         52 NA                                         
 2 603         20 https://en.wikipedia.org/wiki/Area_code_603
 3 970         20 https://en.wikipedia.org/wiki/Area_code_970
 4 207         18 https://en.wikipedia.org/wiki/Area_code_207
 5 802         18 https://en.wikipedia.org/wiki/Area_code_802
 6 406         17 https://en.wikipedia.org/wiki/Area_code_406
 7 888         17 https://en.wikipedia.org/wiki/Area_code_888
 8 530         14 https://en.wikipedia.org/wiki/Area_code_530
 9 877         14 https://en.wikipedia.org/wiki/Area_code_877
10 208         13 https://en.wikipedia.org/wiki/Area_code_208


# Task: Answer the following questions.

1.   Consider the following snip-it of code executed by dplyr above.  How would flip-flopping line #6 and #7 change the output?  Discuss.


<p align='center'><img src="https://drive.google.com/uc?export=view&id=1JEm3NRSA6rFs9jnpRiVCjB9IgVZQlCIA"></p>


2.   Consider the following line of code, line #8 from the code above and it's corresponding output.  Modify this line of code so that AreaCode = 800, 888, and 877 all have NA as these are not real area codes, but used for toll-free numbers.

<strong>Hint:</strong> There is an %in% syntax that is commonly used for strings.  The other option would be to modify the condition with or, i.e. the | syntax. 
<br>
<p align='center'><img src="https://drive.google.com/uc?export=view&id=1gD5fdid290HU6MgzIg9df23aB1vgOzOT"></p>

<p align='center'><img src="https://drive.google.com/uc?export=view&id=1WXpg_70ILWeRZjl8mjSE0mVqgzNbFaec"></p>

<p align='center'><img src="https://drive.google.com/uc?export=view&id=16iSHZCVOuOpgIyXe01QsQwVaIjwi-KVw"></p>


3.   The process followed above was to pre-process the data file to include longitude, latitude, and Phone.  This data was then read into R and R was used to further seperate the string to obtain the area code.  Suppose sed was used instead to separate out the area code.  How would the search & replace work in sed to achieve this?  Discuss.  



<p align='center'><img src="https://drive.google.com/uc?export=view&id=1FWjwi21pZ8fS-WxWYJxjFGWD_qeUWJHV"></p>
